// <auto-generated />
namespace LocallySourced.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1000Ladders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1000Ladders));
        
        string IMigrationMetadata.Id
        {
            get { return "201603130908370_1000 Ladders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
